{% set name = "minio-server" %}
{% set version = "2025-04-03T14-56-28Z" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", ".")|replace("T", ".")|replace("Z", "") }}

source:
  url: https://github.com/minio/minio/archive/RELEASE.{{ version }}.tar.gz
  sha256: 2b33f0bb1da897a15c0bcdb21d30990728d172aba6fe7b71c67822e9b8e9222b
  patches:
    # patch gen-ldflags.go to not use `git` to detect the git commit hash
    # instead use GitHub API (see build/script_env/GIT_TAG and GIT_COMMIT in build scripts)
    - patches/0001-commitID.patch

build:
  number: 0
  script_env:
    - GIT_TAG=RELEASE.{{ version }}
    - GIT_TIME={{ version }}

requirements:
  build:
    - {{ compiler("go-nocgo") }}
    - curl
    - go-licenses
    - jq  # [not win]
    - m2w64-jq  # [win]

test:
  commands:
    - minio --version

about:
  home: https://min.io
  license: AGPL-3.0-only
  license_family: AGPL
  license_file:
    - LICENSE
    - library_licenses/
    - manual_licenses/
  summary: High Performance Object Storage for AI
  description: |
    MinIO is a High Performance Object Storage released under GNU Affero General Public License v3.0.
    It is API compatible with Amazon S3 cloud storage service. Use MinIO to build high performance
    infrastructure for machine learning, analytics and application data workloads.
  doc_url: https://min.io/docs/minio
  dev_url: https://github.com/minio/minio

extra:
  recipe-maintainers:
    - kenodegard
    - pavelzw
